#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CURSOR_CONFIG_ROOT="${CURSOR_CONFIG_ROOT:-$ROOT}"
CATALOG="${CURSOR_CONFIG_ROOT}/commands/commands.md"
BEGIN_MARKER="<!-- BEGIN GENERATED:COMMANDS_ROSTER -->"
END_MARKER="<!-- END GENERATED:COMMANDS_ROSTER -->"
MODE="write"

die() {
  echo "sync-commands-catalog: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: ./tools/cursor/sync-commands-catalog.sh [--check]

Options:
  --check  Fail when generated roster content is stale.
USAGE
}

escape_table_cell() {
  sed 's/|/\\|/g'
}

function_slash() {
  local function_file="$1" slash
  slash="$(sed -n 's/^\*\*Slash:\*\* //p' "$function_file" | head -n 1)"
  if [[ "$slash" == \`*\` ]]; then
    slash="${slash#\`}"
    slash="${slash%\`}"
  fi
  printf '%s' "$slash"
}

assert_markers() {
  local begin_count end_count
  begin_count="$(grep -Fc "$BEGIN_MARKER" "$CATALOG" || true)"
  end_count="$(grep -Fc "$END_MARKER" "$CATALOG" || true)"
  [[ "$begin_count" == "1" ]] || die "expected exactly one begin marker in ${CATALOG}"
  [[ "$end_count" == "1" ]] || die "expected exactly one end marker in ${CATALOG}"
}

extract_existing_block() {
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { in_block = 1; next }
    $0 == end { exit }
    in_block { print }
  ' "$CATALOG"
}

generate_block() {
  local command_file rel base ns slash signature signature_cell public_link
  local function_file function_rel route slash_route function_link function_cell
  local function_links
  local -a namespace_functions

  printf '%s\n' "_Generated by \`tools/cursor/sync-commands-catalog.sh\`; do not edit this block by hand._"
  printf '\n'
  printf '%s\n' "| Slash | Signature | Public router | Private functions |"
  printf '%s\n' "| --- | --- | --- | --- |"

  while IFS= read -r command_file; do
    rel="${command_file#"${CURSOR_CONFIG_ROOT}/commands/"}"
    base="$(basename "$command_file")"
    [[ "$base" == "commands.md" ]] && continue

    ns="${base%.md}"
    slash="$(awk '/^# / { print $2; exit }' "$command_file")"
    signature="$(sed -n 's/^\*\*Signature:\*\* //p' "$command_file" | head -n 1)"
    [[ -n "$signature" ]] || signature="$slash"
    if [[ "$signature" == \`*\` ]]; then
      signature="${signature#\`}"
      signature="${signature%\`}"
    fi
    signature_cell="$(printf '%s' "$signature" | escape_table_cell)"
    public_link="[${ns}](${rel})"

    namespace_functions=()
    while IFS= read -r function_file; do
      namespace_functions+=("$function_file")
    done < <(find "${CURSOR_CONFIG_ROOT}/_functions/${ns}" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort)

    if ((${#namespace_functions[@]} == 0)); then
      function_cell="n/a"
    else
      function_links=""
      for function_file in "${namespace_functions[@]}"; do
        function_rel="${function_file#"${CURSOR_CONFIG_ROOT}/_functions/"}"
        route="$(function_slash "$function_file")"
        if [[ -n "$route" && "$route" == "/${ns} "* ]]; then
          route="${route#"/${ns} "}"
        elif [[ -n "$route" && "$route" == "/${ns}" ]]; then
          route="${ns}"
        else
          route="$(basename "$function_file" .md)"
        fi
        function_link="[${route}](../_functions/${function_rel})"
        if [[ -n "$function_links" ]]; then
          function_links="${function_links}, "
        fi
        function_links="${function_links}${function_link}"
      done
      function_cell="$function_links"
    fi

    printf "| \`%s\` | \`%s\` | %s | %s |\n" "$slash" "$signature_cell" "$public_link" "$function_cell"
  done < <(find "${CURSOR_CONFIG_ROOT}/commands" -maxdepth 1 -type f -name '*.md' | sort)

  printf '\n'
  printf '%s\n' "| Route | Private function |"
  printf '%s\n' "| --- | --- |"
  while IFS= read -r function_file; do
    function_rel="${function_file#"${CURSOR_CONFIG_ROOT}/_functions/"}"
    ns="$(dirname "$function_rel")"
    route="$(basename "$function_file" .md)"
    slash_route="$(function_slash "$function_file")"
    if [[ -z "$slash_route" ]]; then
      slash_route="/${ns} ${route}"
      if [[ "$ns" == "test" && "$route" == "run" ]]; then
        slash_route="/test"
      fi
    fi
    function_link="[${function_rel}](../_functions/${function_rel})"
    function_cell="$(printf '%s' "$slash_route" | escape_table_cell)"
    printf "| \`%s\` | %s |\n" "$function_cell" "$function_link"
  done < <(find "${CURSOR_CONFIG_ROOT}/_functions" -type f -name '*.md' | sort)
}

write_block() {
  local generated_file="$1" tmp_file
  tmp_file="$(mktemp)"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v generated="$generated_file" '
    $0 == begin {
      print
      while ((getline line < generated) > 0) {
        print line
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$CATALOG" >"$tmp_file"
  mv "$tmp_file" "$CATALOG"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

[[ -f "$CATALOG" ]] || die "missing catalog: $CATALOG"
assert_markers

generated="$(mktemp)"
existing="$(mktemp)"
trap 'rm -f "$generated" "$existing"' EXIT

generate_block >"$generated"
extract_existing_block >"$existing"

if ! cmp -s "$generated" "$existing"; then
  if [[ "$MODE" == "check" ]]; then
    die "generated roster is stale in ${CATALOG}; run ./tools/cursor/sync-commands-catalog.sh"
  fi
  write_block "$generated"
  echo "sync-commands-catalog: updated ${CATALOG}"
  exit 0
fi

if [[ "$MODE" == "check" ]]; then
  echo "sync-commands-catalog: OK"
else
  echo "sync-commands-catalog: already up to date"
fi
