#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$(cd "$(dirname "$0")/../../../.." && pwd)}"
# shellcheck source=tests/helpers/assert.sh
source "$ROOT/tests/helpers/assert.sh"

tmp="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp"
}
trap cleanup EXIT

cfg="$tmp/cursor"
cp -R "$ROOT/cursor" "$cfg"
catalog="$cfg/commands/commands.md"

tmp_catalog="$tmp/commands.md"
awk '
  !updated && /_Generated by `tools\/cursor\/sync-commands-catalog.sh`; do not edit this block by hand\._/ {
    sub(/do not edit this block by hand\._/, "intentionally stale._")
    updated = 1
  }
  { print }
' "$catalog" >"$tmp_catalog"
mv "$tmp_catalog" "$catalog"

set +e
output="$({
  CURSOR_CONFIG_ROOT="$cfg" \
  "$ROOT/tools/cursor/sync-commands-catalog.sh" --check
} 2>&1)"
status=$?
set -e

[[ $status -ne 0 ]] || fail "sync-commands-catalog --check should fail when generated roster is stale"
assert_contains "$output" "generated roster is stale"

echo "PASS: sync-commands-catalog check fails when generated roster is stale"
