#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$(cd "$(dirname "$0")/../../../.." && pwd)}"
# shellcheck source=tests/helpers/assert.sh
source "$ROOT/tests/helpers/assert.sh"

tmp="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp"
}
trap cleanup EXIT

cfg="$tmp/cursor"
cp -R "$ROOT/cursor" "$cfg"
contract="$cfg/_core/role.md"

tmp_contract="$tmp/role.md"
awk '
  !updated && /_Generated by `tools\/cursor\/sync-roles-roster.sh`; do not edit this block by hand\._/ {
    sub(/do not edit this block by hand\._/, "intentionally stale._")
    updated = 1
  }
  { print }
' "$contract" >"$tmp_contract"
mv "$tmp_contract" "$contract"

set +e
output="$({
  CURSOR_CONFIG_ROOT="$cfg" \
  "$ROOT/tools/cursor/sync-roles-roster.sh" --check
} 2>&1)"
status=$?
set -e

[[ $status -ne 0 ]] || fail "sync-roles-roster --check should fail when generated roster is stale"
assert_contains "$output" "generated roster is stale"

echo "PASS: sync-roles-roster check fails when generated roster is stale"
